### ISSUE TITLE
Unable to use with distillery release remote_console

### ISSUE THREAD

**Issue by Freyskeyd** [uberbrodt/caravan#4]
Hello,

I was trying to connect to a running node.
I'm connected in the container and I tried to run the `remote_console` (of distillery release) but it keep saying that the node isn't running.

How can I connect to it when using Caravan with Consul DNS?

I can't find any solution by my own.

THank's!

**Comment by uberbrodt** [comment]
Hi, thanks for using Caravan!

I looked into Distillery's `remote_console` script and it looks like it's setting up an erl shell, but it's using the default kernel options to connect using `epmd`, which will fail when your remote app is using Caravan correctly.

I suggest using your own script to open remote shells to apps using Caravan. This is a script I use in the root of my projects:

```
#! /bin/bash

if [ -z "$1" ]
    then
        echo "Must pass in a value for -name like 'node3434'"
        exit 1
fi
iex --erl "-pa ../../_build/dev/lib/caravan/ebin -proto_dist Elixir.Caravan.Epmd.Dist" \
--erl "-start_epmd false -epmd_module Elixir.Caravan.Epmd.Client"  \
--name "local-$1@127.0.0.1" --cookie "$COOKIE" --hidden --remsh "$2"
```

You can use it like this `./remsh_start 3333 myapp-3434@somehost.com`

**Comment by Freyskeyd** [comment]
thank's for this quick response.

I tried your script but it won't connect.
Do I need to open specific port?
the error is something like:

```
Erlang/OTP 21 [erts-10.2.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

Could not contact remote node myservice-4371@app-1.node.dev-eu_aws_1.consul, reason: :nodedown. Aborting...

```

**Comment by uberbrodt** [comment]
So you need to make sure that both ports (local and remote) are open and that those urls are resolvable. So you should be able to `dig` (or some equivalent means of verifying a domain name) `app-1.node.dev-eu_aws_1.consul` from the machine you're trying to connect from, and get an IP address back. You can use `nmap` to check which ports are open (distribution is done via TCP/IP).
