### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by johnnyplaydrums** [uberbrodt/caravan#6]
Hello! I am trying to integrate caravan into our service so that I can deploy it to our nomad/consul cluster. Thanks for this great library. I added `{:caravan, "~> 1.0.0"},` to `mix.exs` and ran `mix.deps get`. But when I try to compile, I get this error:
```
$ mix deps.compile caravan
==> caravan
Compiling 8 files (.ex)

== Compilation error in file lib/caravan/cluster/dns_strategy.ex ==
** (CompileError) lib/caravan/cluster/dns_strategy.ex:52: module Cluster.Strategy is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/1
    lib/caravan/cluster/dns_strategy.ex:52: Caravan.Cluster.DnsStrategy (module)
```

I also tried explicitly adding `{:libcluster, "~> 3.2.1"}` to `mix.exs` and confirmed that `libcluster` was in my `deps` directory, but I still got the same error when I try to build the app or run `mix deps.compile caravan`. Any ideas?

**Comment by uberbrodt** [comment]
Offhand it looks like it could be one of a few things:

1. [Libcluster](https://github.com/bitwalker/libcluster) dependency isn't present in your app.
2. Libcluster changed the contract and I'm not aware of it.

I'm planning to look into this and another issue on Sunday but if you
could check that you have :libcluster in your deps and tell me the
version (should be in  mix.lock) I would appreciate it.

**Comment by uberbrodt** [comment]
Yep, so I have libcluster set as an optional dependency, so I'm 99% sure that's the issue you're seeing. I'll push an update to make it required soon.

**Comment by johnnyplaydrums** [comment]
Hi @uberbrodt, thanks for your response! You're right, the optional dependency was the issue! I thought I had tried adding `libcluster` to my deps explicitly, but I must have not compiled it when I tested. At any rate, adding `{:libcluster, "~> 3.2.1"}` to my deps and compiling that first did the trick. And yes making it required would be great. Thanks for the help!
